### PR TITLE
Adding a button to toggle the visibility of the day picker

### PR DESCRIPTION
**Pull request by srikriss**
Hi Somesh,

I have added a button to toggle the Visibility of the day picker for the following issue https://github.com/someshkar/covid19india-network/issues/57.

Let me know if any changes are required.

### CODE REVIEW

**Comment by sibeshkar** [comment]
Hey thanks! Can you change the styles a bit so it looks like this. bg white, border-radius 5px and width 200px.

image

**Comment by srikriss** [comment]
Day picker has width of 280 px. Setting the button width to 200px looks like this

image

**Comment by sibeshkar** [comment]
Why is it abruptly moving to the left when expanded? Should stay in place, then the width won't matter.

**Comment by srikriss** [comment]
If difference in the widths of day picker and button is okay, then it will look like this

image

**Comment by sibeshkar** [comment]
Looks good. Do push

**Pull request merged**
