### PR TITLE
fixes issue #13. Added zoom in/out buttons

### PR DESCRIPTION
**Pull request by MANEESH-P**

### CODE REVIEW

**Comment by sibeshkar** [comment]
Nice! We just added a date selector on the bottom right of the graph. Can you shift this to the bottom left? Thanks :)

**Comment by MANEESH-P** [comment]
Sure, will do it.

**Comment by MANEESH-P** [comment]
Zoom buttons moved to the left.

**Comment by sibeshkar** [comment]
One last change. Make the buttons slightly smaller, make them laid out horizontally, and just make sure it works on mobile too.

**Comment by MANEESH-P** [comment]
Made the changes and it is working fine on mobile too.

**Pull request merged**
