### PR TITLE
feat (Patient selection UI): Zoom to selected patient

### PR DESCRIPTION
**Pull request by SahajR**
This is a basis for the search feature [#21](https://github.com/someshkar/covid19india-network/issues/21). 

Currently, a useEffect hook reacts to a selected user in the graph. I have currently rewritten the store state to remove the redundant `selected` field.

For the search by Id to work, we can find the coords of the patient (after finding it by id) through the vis.js API. Let me know if I should go ahead with this next step. I'll also add a search input in the side panel for the purpose.

Waiting for your response after the review.

### CODE REVIEW

**Comment by someshkar** [comment]
Can you make a search and zoom to patient UI? Like a searchbar where you can find a patient by Id/City/Travel History and zoom to the patient on the map?

**Comment by someshkar** [comment]
Also please resolve the merge conflicts with the latest commit to the master branch.

**Comment by SahajR** [comment]
Alright.

**Comment by SahajR** [comment]
@someshkar Added search by patient id. Review if this workflow works. If so, I will add search capabilities with other criteria and finish this feature to close #21

**Comment by someshkar** [comment]
@SahajR this works really well! Merging.

**Pull request merged**
